config/routes.rb
Rails.application.routes.draw do

 resources :tasks
get "admin/index"
get "admin/invite"

match ':controller(/:action(/:id))', :via => [:get,:post]
devise_for :users, controllers: { sessions: 'users/sessions' }



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#,:confirmable

   #has_many :daily_statuses
   #has_many :activites, :through =>:daily_statuses
   #accepts_nested_attributes_for :activite

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout 'main'

  def index
  end

  def invite

  end

  def show_projects


  end

  def show_employees



  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


	
	#def after_sign_in_path_for(resource)
	 #  admin_index_path #your path
	#end

  before_action :configure_permitted_parameters, if: :devise_controller?
 protected
	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :first_name, :last_name, :employees_id, :manager_id, :username, :location_id, :project_id, :department_id, :git_id) }
  	end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout 'main'
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :task_perform_today, :git_link, :jira_link, :remarks)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  layout 'main'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'main'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'main'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'main'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

 # GET /resource/sign_up
  def new
     super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     super(resource)
      if @user.admin?
      admin_index_path #your path
    else
         tasks_path 
    end
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'main'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
    super
    @user=User.where(params[:email]).first
   end

  # POST /resource/sign_in
   def after_sign_in_path_for(resource)
      if @user.admin?
      admin_index_path #your path
    else
         tasks_path 
    end
  end

  # DELETE /resource/sign_out
   #def destroy
    #super
   #end
   

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


  #def create
    # custom sign-in code

    #redirect_to(:controller => 'statusreport', :action => 'status') 
  end
  

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  layout 'main'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	#sign_in_and_redirect @user

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

<%= link_to "Invite Employees", :action => 'invite' %><br>
<%= link_to "show Employees", :action => 'show_employees' %><br>
<%= link_to "show projects", :action => 'show_projects' %><br>

app/views/admin/invite.html.erb
<h1>Admin#invite</h1>
<p>Find me in app/views/admin/invite.html.erb</p>
<%= link_to "<< index", :action => 'index' %><br>
<%= form_for(:admin,:url => { :controller => 'admin',:action => 'invite'} )do |f| %>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email  %>
    <%= f.submit "invite" %>

<% end %>

app/views/admin/show_employees.html.erb
<h1>Admin#show_employee</h1>
<p>Find me in app/views/admin/show_employee.html.erb</p>
<%= link_to "<< index", :action => 'index' %><br>

app/views/admin/show_projects.html.erb
<h1>Admin#show_project</h1>
<p>Find me in app/views/admin/show_project.html.erb</p>
<%= link_to "<< index", :action => 'index' %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Status</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   			 <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><strong>status update</strong></title>
	<%= stylesheet_link_tag('application', :media => 'all', 'data-turbolinks-track': 'reload') %>
</head>
<body>
	<div id="header">
		
		<ul class="navbar" >

			<li><%= link_to('Home' , :controller =>"statusreport", :action => "home") %></li>
			<li><% if user_signed_in? %>
  			<li>
  				<%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
 			 </li>
			<% else %>
  			<li>
  			<%= link_to('Login', new_user_session_path)  %>  
  			</li>
			<% end %>
			</li>
			<li><% if user_signed_in? %>
  			<li>
  			<%= link_to('Edit registration', edit_user_registration_path) %>
  			</li>
			<% else %>
  			<li>
  			<%= link_to('Register', new_user_registration_path)  %>
  			</li>
			<% end %></li>
			<li><%= link_to('About us' , '#')%></li>
			<li><%= link_to('contact' , '#')%></li>
			</ul>
			</div>

	<div id="content">
		<%= yield %>

	</div>

	<div id="footer">
		<p> &copy; navtech@status_update  </p>
	</div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :task_content %>
  </div>

  <div class="field">
    <%= form.label :task_perform_today %>
    <%= form.text_area :task_perform_today, id: :task_task_perform_today %>
  </div>

  <div class="field">
    <%= form.label :git_link %>
    <%= form.text_field :git_link, id: :task_git_link %>
  </div>

  <div class="field">
    <%= form.label :jira_link %>
    <%= form.text_field :jira_link, id: :task_jira_link %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks, id: :task_remarks %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Task perform today</th>
      <th>Git link</th>
      <th>Jira link</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.task_perform_today %></td>
        <td><%= task.git_link %></td>
        <td><%= task.jira_link %></td>
        <td><%= task.remarks %></td>
        <td><%= link_to 'Show', task %></td>
       
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Task perform today:</strong>
  <%= @task.task_perform_today %>
</p>

<p>
  <strong>Git link:</strong>
  <%= @task.git_link %>
</p>

<p>
  <strong>Jira link:</strong>
  <%= @task.jira_link %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @task.remarks %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'submit', tasks_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>